FROM ruby:3.3-slim

WORKDIR /app

COPY Gemfile Gemfile.lock* ./

RUN bundle install

COPY src/app.rb .

EXPOSE 4567

ARG SINATRA_LOCAL_CACHE_DEFAULT_TIMEOUT
ARG CODE_ENV
ENV LOCAL_CACHE_DEFAULT_TIMEOUT=$SINATRA_LOCAL_CACHE_DEFAULT_TIMEOUT
ENV CODE_ENV=$CODE_ENV

CMD ["ruby", "app.rb"]